services:
  chainlit:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: chainlit
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./src:/app
      - ./prompts:/prompts
      - ./transcripts:/app/transcripts
      - ./chainlit.db:/app/chainlit.db
    working_dir: /app
    restart: unless-stopped
