name: Security Audit
on: [push]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for Gitleaks to scan history

      #  Prevent API Key leaks
      - name: Check for Secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Check for vulnerable Python packages
      - name: Safety Check
        uses: pyupio/safety-action@v1
        with:
          api-key: "" 